#include "models/settings.h"
#include "include/global_constants.h"
#include <QObject>
#include <algorithm>
#include <array>
#include <audio_types.h>
#include <cstddef>
#include <cstdint>
#include <fft_window.h>
#include <stdexcept>

Settings::Settings(QObject* aParent)
  : QObject(aParent)
  , mColorMapLUTs()
{
    // Initialize default color maps
    for (ChannelCount ch = 0; ch < GKMaxChannels; ch++) {
        SetColorMap(ch, KDefaultColorMaps.at(ch));
    }
}

void
Settings::SetFFTSettings(const FFTSize aTransformSize, const FFTWindow::Type aWindowType)
{
    if (mFFTSize != aTransformSize || mWindowType != aWindowType) {
        mFFTSize = aTransformSize;
        mWindowType = aWindowType;
        emit FFTSettingsChanged();     // NOLINT(misc-include-cleaner) // emit is generated by moc
        emit DisplaySettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
    }
}

void
Settings::SetWindowScale(const WindowScale aScale)
{
    if (std::ranges::find(KValidWindowScales, aScale) == KValidWindowScales.end()) {
        throw std::invalid_argument("Invalid window scale");
    }

    mWindowScale = aScale;
    emit DisplaySettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
}

void
Settings::SetColorMap(ChannelCount aChannel, ColorMapType aType)
{
    // Helper to set a gradient color map
    auto setGradientColorMap = [this, aChannel](bool enableRed, bool enableGreen, bool enableBlue) {
        for (size_t i = 0; i < KColorMapLUTSize; i++) {
            const auto intensity = static_cast<uint8_t>(i);
            mColorMapLUTs.at(aChannel).at(i) =
              ColorMapEntry{ .r = enableRed ? intensity : uint8_t{ 0 },
                             .g = enableGreen ? intensity : uint8_t{ 0 },
                             .b = enableBlue ? intensity : uint8_t{ 0 } };
        }
    };

    switch (aType) {
        case ColorMapType::White:
            setGradientColorMap(true, true, true);
            break;
        case ColorMapType::Red:
            setGradientColorMap(true, false, false);
            break;
        case ColorMapType::Green:
            setGradientColorMap(false, true, false);
            break;
        case ColorMapType::Blue:
            setGradientColorMap(false, false, true);
            break;
        case ColorMapType::Cyan:
            setGradientColorMap(false, true, true);
            break;
        case ColorMapType::Magenta:
            setGradientColorMap(true, false, true);
            break;
        case ColorMapType::Yellow:
            setGradientColorMap(true, true, false);
            break;
        default:
            throw std::invalid_argument("Settings::SetColorMap: Unsupported color map type");
    }

    mSelectedColorMaps.at(aChannel) = aType;
    emit DisplaySettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
}

void
Settings::SetApertureMinDecibels(const float aMinDecibels)
{
    mApertureMinDecibels = aMinDecibels;
    emit DisplaySettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
}

void
Settings::SetApertureMaxDecibels(const float aMaxDecibels)
{
    mApertureMaxDecibels = aMaxDecibels;
    emit DisplaySettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
}
