#include "models/settings.h"
#include "include/global_constants.h"
#include <QObject>
#include <cstddef>
#include <cstdint>
#include <fft_window.h>
#include <stdexcept>

Settings::Settings(QObject* aParent)
  : QObject(aParent)
  , mColorMapLUTs()
{
    // Initialize default color maps
    for (size_t ch = 0; ch < gkMaxChannels; ch++) {
        SetColorMap(ch, kDefaultColorMaps.at(ch));
    }
}

void
Settings::SetFFTSettings(const size_t aTransformSize, const FFTWindow::Type aWindowType)
{
    if (aTransformSize == 0 || (aTransformSize & (aTransformSize - 1)) != 0) {
        throw std::invalid_argument("FFT size must be a power of two and greater than zero");
    }

    if (mFFTSize != aTransformSize || mWindowType != aWindowType) {
        mFFTSize = aTransformSize;
        mWindowType = aWindowType;
        emit FFTSettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
    }
}

void
Settings::SetWindowStride(const size_t aStride)
{
    if (aStride == 0) {
        throw std::invalid_argument("Window stride must be greater than zero");
    }

    if (mWindowStride != aStride) {
        mWindowStride = aStride;
        emit WindowStrideChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
    }
}

void
Settings::SetColorMap(size_t aChannel, ColorMapType aType)
{
    // Helper to set a gradient color map
    auto setGradientColorMap = [this, aChannel](bool enableRed, bool enableGreen, bool enableBlue) {
        for (size_t i = 0; i < kColorMapLUTSize; i++) {
            const auto intensity = static_cast<uint8_t>(i);
            mColorMapLUTs.at(aChannel).at(i) =
              ColorMapEntry{ .r = enableRed ? intensity : uint8_t{ 0 },
                             .g = enableGreen ? intensity : uint8_t{ 0 },
                             .b = enableBlue ? intensity : uint8_t{ 0 } };
        }
    };

    switch (aType) {
        case ColorMapType::kWhite:
            setGradientColorMap(true, true, true);
            break;
        case ColorMapType::kRed:
            setGradientColorMap(true, false, false);
            break;
        case ColorMapType::kGreen:
            setGradientColorMap(false, true, false);
            break;
        case ColorMapType::kBlue:
            setGradientColorMap(false, false, true);
            break;
        case ColorMapType::kCyan:
            setGradientColorMap(false, true, true);
            break;
        case ColorMapType::kMagenta:
            setGradientColorMap(true, false, true);
            break;
        case ColorMapType::kYellow:
            setGradientColorMap(true, true, false);
            break;
        default:
            throw std::invalid_argument("Settings::SetColorMap: Unsupported color map type");
    }
}