#include "models/settings.h"
#include <cstddef>
#include <fft_window.h>
#include <stdexcept>

void
Settings::SetFFTSettings(const size_t aTransformSize, const FFTWindow::Type aWindowType)
{
    if (aTransformSize == 0 || (aTransformSize & (aTransformSize - 1)) != 0) {
        throw std::invalid_argument("FFT size must be a power of two and greater than zero");
    }

    if (mFFTSize != aTransformSize || mWindowType != aWindowType) {
        mFFTSize = aTransformSize;
        mWindowType = aWindowType;
        emit FFTSettingsChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
    }
}

void
Settings::SetWindowStride(const size_t aStride)
{
    if (aStride == 0) {
        throw std::invalid_argument("Window stride must be greater than zero");
    }

    if (mWindowStride != aStride) {
        mWindowStride = aStride;
        emit WindowStrideChanged(); // NOLINT(misc-include-cleaner) // emit is generated by moc
    }
}
