#include "settings_controller.h"
#include "models/settings.h"
#include <QAudioDevice>

void
SettingsController::StartRecording(const QAudioDevice& aDevice,
                                   const int aSampleRate,
                                   const int aChannelCount)
{
    mSettings->SetAudioInputSettings(aDevice, aSampleRate, aChannelCount);
    emit StartAudioRecording(); // NOLINT(misc-include-cleaner) // emit is generated by moc
}
