#include "settings_controller.h"
#include <QAudioDevice>

void
SettingsController::StartRecording(const QAudioDevice& aDevice,
                                   const int aSampleRate,
                                   const int aChannelCount)
{
    // NOLINTNEXTLINE(misc-include-cleaner) // emit is generated by moc
    emit StartAudioRecording(aDevice, aChannelCount, aSampleRate);
}
