#!/usr/bin/env python3
# Spectro-v3 -- Real-time spectrum analyzer
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2025-2026 Chris "Kai" Frederick

"""
Generate colormap LUT data for spectro-v3 from matplotlib colormaps.

This script extracts RGB values from matplotlib's perceptually uniform
colormaps (viridis, plasma, inferno, magma) and generates a C++ header
file with pre-computed ColorMapEntry arrays ready for direct use.

Usage:
    python3 scripts/generate_colormap_data.py

Output:
    qt6_gui/include/colormap_data.h

Requirements:
    - Python 3.6+
    - matplotlib
    - numpy

Note: This script is only needed to regenerate the colormap data.
Building spectro-v3 does not require Python or matplotlib.
"""

import sys
from pathlib import Path
from typing import List, Tuple
import matplotlib.pyplot as plt


def get_colormap_rgb(name: str, num_samples: int = 256) -> List[Tuple[int, int, int]]:
    """
    Extract RGB values from a matplotlib colormap.

    Args:
        name: Name of the matplotlib colormap
        num_samples: Number of samples to extract (default: 256)

    Returns:
        List of (r, g, b) tuples with values in range [0, 255]
    """
    cmap = plt.get_cmap(name)
    rgb_values = []

    for i in range(num_samples):
        # normalized position in colormap 0.0 - 1.0
        x = i / (num_samples - 1)

        # Get RGBA from colormap (values are 0.0 - 1.0)
        rgba = cmap(x)

        # Convert to 8-bit RGB
        r = int(round(rgba[0] * 255))
        g = int(round(rgba[1] * 255))
        b = int(round(rgba[2] * 255))

        rgb_values.append((r, g, b))

    return rgb_values


def format_colormap_cpp(name: str, rgb_values: List[Tuple[int, int, int]]) -> str:
    """
    Format colormap data as a C++ constexpr array.

    Args:
        name: Name of the colormap (e.g., 'viridis')
        rgb_values: List of (r, g, b) tuples

    Returns:
        C++ code string defining the array
    """
    # Create identifier (e.g., 'viridis' -> 'GKViridisLUT')
    identifier = f"GK{name.capitalize()}LUT"

    output = f"/// @brief {name.capitalize()} colormap lookup table (256 entries)\n"
    output += f"constexpr std::array<Settings::ColorMapEntry, 256> {identifier} = {{{{"

    # Format entries, 4 per line for readability
    for i in range(len(rgb_values)):
        if i % 4 == 0:
            output += "\n   "
        r, g, b = rgb_values[i]
        output += f" {{{r:3d}, {g:3d}, {b:3d}}},"
    output += "\n}};\n"
    return output


def generate_header(output_path: Path) -> None:
    """
    Generate the complete C++ header file with all colormaps.

    Args:
        output_path: Path to the output header file
    """
    # Colormaps to generate
    colormaps = ["viridis", "plasma", "inferno", "magma"]

    # Generate header content
    header_lines = [
        "// Spectro-v3 -- Real-time spectrum analyzer",
        "// SPDX-License-Identifier: GPL-3.0-only",
        '// Copyright (C) 2025-2026 Chris "Kai" Frederick',
        "//",
        "// ============================================================================",
        "// THIS FILE IS AUTO-GENERATED BY scripts/generate_colormap_data.py",
        "// DO NOT EDIT MANUALLY - Changes will be overwritten",
        "// ============================================================================",
        "//",
        "// Colormap data from matplotlib's viridis family",
        "// Originally created by Nathaniel J. Smith, Stefan van der Walt, and Eric Firing",
        "// Released under CC0 1.0 Universal Public Domain Dedication",
        "// Source: https://github.com/BIDS/colormap",
        "//",
        "// clang-format off",
        "// NOLINTBEGIN(modernize-use-designated-initializers)",
        "",
        "#pragma once",
        "",
        '#include "models/settings.h"',
        "",
    ]

    # Generate data for each colormap
    for i, cmap_name in enumerate(colormaps):
        print(f"Extracting {cmap_name}...")
        rgb_values = get_colormap_rgb(cmap_name)
        header_lines.append(format_colormap_cpp(cmap_name, rgb_values))
    
    header_lines.append("// NOLINTEND(modernize-use-designated-initializers)")

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header_lines))


def main():
    """Main entry point."""
    # Determine paths relative to script location
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    output_path = project_root / "qt6_gui" / "include" / "colormap_data.h"

    print("Spectro-v3 Colormap Data Generator")
    print("==================================")
    print(f"Project root: {project_root}")
    print(f"Output file: {output_path}")
    print()

    generate_header(output_path)
    print("\nDone!")


if __name__ == "__main__":
    main()
